Repository cornell-dti/campus-density-android, pull requests merged in 2020-02, with the labels that each got.

#40 Fixed chips and small screen layouts
  Density/app/src/main/res/drawable/chip_color_toggle.xml
  Density/app/src/main/res/layout/facilities_activity.xml
  Density/app/src/main/res/layout/facility_info_page.xml
  Density/app/src/main/res/values/chips.xml
  Density/app/src/main/res/values/styles.xml
Labels: bug

#41 Update facility card layout and chip spacing
  Density/app/src/main/res/layout/facility_card_layout.xml
  Density/app/src/main/res/layout/facility_info_page.xml
  Density/app/src/main/res/values-w360dp/chips.xml
  Density/app/src/main/res/values-w480dp/chips.xml
  Density/app/src/main/res/values/chips.xml
Labels: code, feature

#36 Menus API and UI
  Density/app/src/main/AndroidManifest.xml
  Density/app/src/main/java/org/cornelldti/density/density/data/MenuClass.kt
  Density/app/src/main/java/org/cornelldti/density/density/facilities/FacilitiesActivity.kt
  Density/app/src/main/java/org/cornelldti/density/density/facilitydetail/FacilityInfoPage.kt
  Density/app/src/main/java/org/cornelldti/density/density/facilitydetail/MenuListAdapter.kt
  Density/app/src/main/java/org/cornelldti/density/density/network/API.kt
  Density/app/src/main/java/org/cornelldti/density/density/network/Endpoints.kt
  Density/app/src/main/java/org/cornelldti/density/density/network/JsonParser.kt
  Density/app/src/main/java/org/cornelldti/density/density/util/FluxUtil.kt
  Density/app/src/main/res/layout/facility_info_page.xml
  Density/app/src/main/res/layout/menu_category_list_item.xml
  Density/app/src/main/res/layout/menu_food_list_item.xml
  Density/app/src/main/res/values/strings.xml
  Density/app/src/main/res/values/styles.xml
Labels: big, feature
